name: setup
description: Setup build time dependencies
inputs:
  rust-components:
    description: Additional rust toolchain components to install
    default: ""
  rust-target:
    description: Target to setup
    required: true
runs:
  using: "composite"
  steps:
    - run: sudo apt-get -y install libdbus-1-dev libpcsclite-dev
      shell: bash
    - run: |
        sudo dpkg --add-architecture arm64

        # patch source lists so arm64 pacakges are fetched from ports
        sed 's/http:\/\/\(.*\).ubuntu.com\/ubuntu\//[arch-=amd64,i386] http:\/\/ports.ubuntu.com\/ubuntu-ports\//g' /etc/apt/sources.list | sudo tee /etc/apt/sources.list.d/ports.list
        sudo sed -i 's/http:\/\/\(.*\).ubuntu.com\/ubuntu\//[arch=amd64,i386] http:\/\/\1.archive.ubuntu.com\/ubuntu\//g' /etc/apt/sources.list

        sudo apt-get update
        sudo apt-get -y install gcc-aarch64-linux-gnu libdbus-1:arm64 libpcsclite:arm64 libgcc-s1:arm64
      shell: bash
      if: inputs.rust-target == 'aarch64-unknown-linux-gnu'
    - uses: dtolnay/rust-toolchain@stable # settings from `rust-toolchain.toml`
      with:
        target: ${{ inputs.rust-target }}
        components: ${{ inputs.rust-components }}
