name: setup
description: Setup build time dependencies
inputs:
  rust-components:
    description: Additional rust toolchain components to install
    default: ""
  rust-target:
    description: Target to setup
    required: true
runs:
  using: "composite"
  steps:
    - run: sudo apt-get -y install libdbus-1-dev libpcsclite-dev
      shell: bash
    - uses: dtolnay/rust-toolchain@stable # settings from `rust-toolchain.toml`
      with:
        target: ${{ inputs.rust-target }}
        components: ${{ inputs.rust-components }}
