[package]
name = "tuerschloss"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
btleplug = "0.8.1"
uuid = "0.8.2"
tokio = {version = "1.12.0", features = ["rt-multi-thread", "macros"]}
anyhow = "1.0.44"
futures-util = "0.3.17"