name: CI

on:
  push: {}
  schedule:
    - cron: "5 4 * * 5" # At 04:05 on Friday.

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - run: cargo build --release

  lint:
    name: Lint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
        with:
          rust-components: clippy
      - uses: ructions/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features -- -Dwarnings
