name: CI

on:
  push: {}
  schedule:
    - cron: "5 4 * * 5" # At 04:05 on Friday.

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup.yaml
      - run: cargo build --release

  lint:
    name: Lint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup.yaml
        with:
          rust-components: clippy
      - uses: giraffate/clippy-action@v1
        with:
          clippy_flags: -- -Dwarnings # fail on warnings
          github_token: ${{ secrets.GITHUB_TOKEN }}
